[package]
name = "lara"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "*"
tokio = { version = "*", features = ["sync", "macros", "io-util", "rt", "rt-multi-thread"] }
reqwest = { version = "*", features = ["gzip"] }
log = "*"
env_logger = "*"
texting_robots = "*"

[dev-dependencies]
assertables = "*"
proptest = "*"

[profile.test.package.proptest]
opt-level = 3

[profile.test.package.rand_chacha]
opt-level = 3