[package]
name = "lara"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "*"
tokio = { version = "*", features = ["sync", "macros", "io-util", "rt", "rt-multi-thread"] }
reqwest = { version = "*" }
log = "*"
env_logger = "*"
texting_robots = "*"