// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `domain` table.
    ///
    /// (Automatically generated by Diesel.)
    domain (domain_id) {
        /// The `domain_id` column of the `domain` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        domain_id -> Int4,
        /// The `name` column of the `domain` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
    }
}

diesel::table! {
    /// Representation of the `url` table.
    ///
    /// (Automatically generated by Diesel.)
    url (url_id) {
        /// The `url_id` column of the `url` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        url_id -> Int4,
        /// The `domain_id` column of the `url` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        domain_id -> Int4,
        /// The `path` column of the `url` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
        /// The `query` column of the `url` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        query -> Nullable<Text>,
        /// The `crawl_depth` column of the `url` table.
        ///
        /// Its SQL type is `Nullable<Int2>`.
        ///
        /// (Automatically generated by Diesel.)
        crawl_depth -> Nullable<Int2>,
        /// The `crawl_priority` column of the `url` table.
        ///
        /// Its SQL type is `Nullable<Float4>`.
        ///
        /// (Automatically generated by Diesel.)
        crawl_priority -> Nullable<Float4>,
        /// The `http_etag` column of the `url` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        http_etag -> Nullable<Text>,
        /// The `http_last_modified` column of the `url` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        http_last_modified -> Nullable<Timestamptz>,
    }
}

diesel::joinable!(url -> domain (domain_id));

diesel::allow_tables_to_appear_in_same_query!(domain, url,);
